/*
 * This source file was generated by the Gradle 'init' task
 */
package net.patrykdobrowolski.bookshelf;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.cloud.openfeign.EnableFeignClients;
import org.springframework.data.jpa.repository.config.EnableJpaAuditing;
import org.springframework.data.jpa.repository.config.EnableJpaRepositories;
import org.springframework.scheduling.annotation.EnableScheduling;

@SpringBootApplication
@EnableJpaRepositories
@EnableJpaAuditing
@EnableFeignClients
@EnableScheduling
public class BookShelfBackendApplication {

    static void main(String[] args) {
        SpringApplication.run(BookShelfBackendApplication.class, args);

    }
}
