spring:
  application:
    name: bookshelf-backend
  datasource:
    url: jdbc:postgresql://${POSTGRES_BOOKSHELF_HOST}:${POSTGRES_BOOKSHELF_PORT}/${POSTGRES_BOOKSHELF_DATABASE}
    username: ${POSTGRES_BOOKSHELF_USERNAME}
    password: ${POSTGRES_BOOKSHELF_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: validate
    open-in-view: false
  liquibase:
    enabled: true
    default-schema: public
  data.redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    listener:
      simple:
        concurrency: 5
        max-concurrency: 10
        prefetch: 1
        default-requeue-rejected: false
        retry:
          enabled: true
          max-retries: 3
          initial-interval: 2s
          multiplier: 2
          max-interval: 10s

resilience4j:
  circuitbreaker:
    instances:
      google-books-api:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 60s
        recordExceptions:
          - feign.RetryableException
          - feign.FeignException.InternalServerError
          - feign.FeignException.BadGateway
          - feign.FeignException.ServiceUnavailable
          - java.lang.RuntimeException
        ignoreExceptions:
          - feign.FeignException.NotFound
          - feign.FeignException.BadRequest
      biblioteka-narodowa-api:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 60s
        recordExceptions:
          - feign.RetryableException
          - feign.FeignException.InternalServerError
          - feign.FeignException.BadGateway
          - feign.FeignException.ServiceUnavailable
          - java.lang.RuntimeException
        ignoreExceptions:
          - feign.FeignException.NotFound
          - feign.FeignException.BadRequest
      open-library-api:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 60s
        recordExceptions:
          - feign.RetryableException
          - feign.FeignException.InternalServerError
          - feign.FeignException.BadGateway
          - feign.FeignException.ServiceUnavailable
          - java.lang.RuntimeException
        ignoreExceptions:
          - feign.FeignException.NotFound
          - feign.FeignException.BadRequest
  ratelimiter:
    instances:
      google-books-api:
        limitForPeriod: 2
        limitRefreshPeriod: 1s
        timeoutDuration: 2s
  retry:
    instances:
      google-books-api:
        maxAttempts: 3
        waitDuration: 500
        retryExceptions:
          - feign.FeignException.ServiceUnavailable
rabbitmq:
  command-exchange: command-exchange
  fetch-book-command-queue: fetch-book-command-queue
  fetch-book-command-retry-queue: fetch-book-command-retry-queue
  export-session-command-queue: export-session-command-queue
api:
  google-books:
    url: "https://www.googleapis.com/books/v1"
    api-key: ${GOOGLE_BOOKS_API_KEY:AIzaSyD2l4UXLWcj5PtwZxqWZW4zre9udIabs6Q}
  open-library:
    url: "https://openlibrary.org"
  bn:
    url: "https://data.bn.org.pl"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always # DEV ONLY
  health:
    circuitbreakers:
      enabled: true


server:
  port: 8080
