/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import net.patrykdobrowolski.bookscanner.ScannerBackendApplication;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class ScannerBackendApplicationTest {
    @Test void appHasAGreeting() {
        ScannerBackendApplication classUnderTest = new ScannerBackendApplication();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
